// <auto-generated />
using System;
using ExamSystem.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamSystem.Migrations
{
    [DbContext(typeof(exam_system_entities))]
    partial class exam_system_entitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ExamSystem.Entity.m_admin_user", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("full_name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("password_reset_expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password_reset_token")
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.Property<string>("profile_image")
                        .HasColumnType("longtext");

                    b.Property<short>("role")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("updated_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("updated_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("m_admin_users");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_answer_option", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_correct")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("marks_allocated")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("option_html")
                        .HasColumnType("longtext");

                    b.Property<string>("option_image_url")
                        .HasColumnType("longtext");

                    b.Property<string>("option_text")
                        .HasColumnType("longtext");

                    b.Property<long>("question_id")
                        .HasColumnType("bigint");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_datetime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("question_id");

                    b.ToTable("m_answer_options");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_grade", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("level")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("updated_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("m_grades");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_marking_rule", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<short>("difficulty")
                        .HasColumnType("smallint");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("marks_per_question")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("max_questions")
                        .HasColumnType("int");

                    b.Property<int>("min_questions")
                        .HasColumnType("int");

                    b.Property<decimal>("negative_marks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<short>("question_type")
                        .HasColumnType("smallint");

                    b.Property<string>("rule_name")
                        .HasColumnType("longtext");

                    b.Property<long>("subject_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("updated_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("subject_id");

                    b.ToTable("m_marking_rules");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_question", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("default_marks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<short>("difficulty")
                        .HasColumnType("smallint");

                    b.Property<string>("eco_table_json")
                        .HasColumnType("longtext");

                    b.Property<string>("explanation")
                        .HasColumnType("longtext");

                    b.Property<long>("grade_id")
                        .HasColumnType("bigint");

                    b.Property<string>("hint")
                        .HasColumnType("longtext");

                    b.Property<string>("image_url")
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("m_admin_userid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("negative_marks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("question_html")
                        .HasColumnType("longtext");

                    b.Property<string>("question_text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("question_type")
                        .HasColumnType("smallint");

                    b.Property<long>("subject_id")
                        .HasColumnType("bigint");

                    b.Property<string>("tags_json")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("updated_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("grade_id");

                    b.HasIndex("m_admin_userid");

                    b.HasIndex("subject_id");

                    b.ToTable("m_questions");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_subject", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("int");

                    b.Property<long>("grade_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("pass_marks")
                        .HasColumnType("int");

                    b.Property<int>("total_marks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("updated_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("grade_id");

                    b.ToTable("m_subjects");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_token", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ip_address")
                        .HasColumnType("longtext");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("jwt_token")
                        .HasColumnType("longtext");

                    b.Property<string>("session_token")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_agent")
                        .HasColumnType("longtext");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("session_token")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("m_tokens");
                });

            modelBuilder.Entity("ExamSystem.Entity.t_exam", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("created_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("int");

                    b.Property<string>("exam_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("exam_config_json")
                        .HasColumnType("longtext");

                    b.Property<string>("exam_year")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("examination_center")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("grade_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("m_admin_userid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("pass_marks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("subject_id")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("total_marks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("total_questions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("updated_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("exam_code")
                        .IsUnique();

                    b.HasIndex("grade_id");

                    b.HasIndex("m_admin_userid");

                    b.HasIndex("subject_id");

                    b.ToTable("t_exams");
                });

            modelBuilder.Entity("ExamSystem.Entity.t_exam_question", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("exam_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("marks_allocated")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("question_id")
                        .HasColumnType("bigint");

                    b.Property<int>("question_number")
                        .HasColumnType("int");

                    b.Property<string>("section_name")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("exam_id");

                    b.HasIndex("question_id");

                    b.ToTable("t_exam_questions");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_answer_option", b =>
                {
                    b.HasOne("ExamSystem.Entity.m_question", "question")
                        .WithMany("answer_options")
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_marking_rule", b =>
                {
                    b.HasOne("ExamSystem.Entity.m_subject", "subject")
                        .WithMany("marking_rules")
                        .HasForeignKey("subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subject");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_question", b =>
                {
                    b.HasOne("ExamSystem.Entity.m_grade", "grade")
                        .WithMany()
                        .HasForeignKey("grade_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamSystem.Entity.m_admin_user", null)
                        .WithMany("created_questions")
                        .HasForeignKey("m_admin_userid");

                    b.HasOne("ExamSystem.Entity.m_subject", "subject")
                        .WithMany("questions")
                        .HasForeignKey("subject_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("grade");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_subject", b =>
                {
                    b.HasOne("ExamSystem.Entity.m_grade", "grade")
                        .WithMany("subjects")
                        .HasForeignKey("grade_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("grade");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_token", b =>
                {
                    b.HasOne("ExamSystem.Entity.m_admin_user", "user")
                        .WithMany("created_tokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ExamSystem.Entity.t_exam", b =>
                {
                    b.HasOne("ExamSystem.Entity.m_grade", "grade")
                        .WithMany()
                        .HasForeignKey("grade_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamSystem.Entity.m_admin_user", null)
                        .WithMany("created_exams")
                        .HasForeignKey("m_admin_userid");

                    b.HasOne("ExamSystem.Entity.m_subject", "subject")
                        .WithMany("exams")
                        .HasForeignKey("subject_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("grade");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("ExamSystem.Entity.t_exam_question", b =>
                {
                    b.HasOne("ExamSystem.Entity.t_exam", "exam")
                        .WithMany("exam_questions")
                        .HasForeignKey("exam_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamSystem.Entity.m_question", "question")
                        .WithMany("exam_questions")
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("exam");

                    b.Navigation("question");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_admin_user", b =>
                {
                    b.Navigation("created_exams");

                    b.Navigation("created_questions");

                    b.Navigation("created_tokens");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_grade", b =>
                {
                    b.Navigation("subjects");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_question", b =>
                {
                    b.Navigation("answer_options");

                    b.Navigation("exam_questions");
                });

            modelBuilder.Entity("ExamSystem.Entity.m_subject", b =>
                {
                    b.Navigation("exams");

                    b.Navigation("marking_rules");

                    b.Navigation("questions");
                });

            modelBuilder.Entity("ExamSystem.Entity.t_exam", b =>
                {
                    b.Navigation("exam_questions");
                });
#pragma warning restore 612, 618
        }
    }
}
